### ISSUE TITLE
method.exec returns error after successful software_update from a trigger

### ISSUE THREAD

**Issue by tonym-wrs** [Wind-River/device-cloud-python#100]
software_update runs to successful completion in hdc-python, but method.exec returns error if used within a trigger.

**Comment by tonym-wrs** [comment]
In order for campaign to be used the methods must reliably return success/fail

**Comment by element-82** [comment]
Your ack timeout in the trigger is too short.  See my example:
https://core-portal.hdcstg.net/triggers/report/5a0376f474e9364b200c9a55
