### ISSUE TITLE
Downloading a large file reports timed out 

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#110]
I downloaded a 212 MB file using the Send Files method. After about 20 seconds the method output box in the cloud shows the following:
[
    "Mailbox ack timed out."
]

On the device, the download continues and after 1 minute, the console output shows a timed out message, but the download continues. After about 1 minute and 30 seconds, the console output shows a message to indicate a successful download. The file appears in the directory I specified and seems to have the correct size.

There is a download_timeout attribute in the iot.cfg file, but I'm told that it is not used for regular file downloads. I don't know where the timeout message after 60 seconds is configured, and it's not clear where the 20 second timeout in the cloud comes from.

Logs from the device console are below.

Nov 10 13:35:07 DEBUG: handler.py:984 - Received message on topic "notify/mailbox_activity"
{
  "sessionId": "5a05e79d6466576272636d43", 
  "thingKey": "e8cdb5c5-c3f0-4820-8eef-7506c51b0676-device_manager_py"
}
Nov 10 13:35:07 INFO: handler.py:615 - Recevied notification of mailbox activity
Nov 10 13:35:07 INFO: handler.py:1176 - MQTT queued 0014-1 - Mailbox Check
{
  "command": "mailbox.check", 
  "params": {
    "autoComplete": false
  }
}
Nov 10 13:35:07 DEBUG: handler.py:998 - MQTT sent 0014
Nov 10 13:35:07 DEBUG: handler.py:984 - Received message on topic "reply/0014"
{
  "1": {
    "params": {
      "messages": [
        {
          "command": "method.exec", 
          "expires": "2017-11-10T18:35:10.004Z", 
          "from": "julia.keffer@windriver.com", 
          "id": "5a05f14f74e9364b20408f48", 
          "params": {
            "method": "file_download", 
            "params": {
              "file_name": "vmlinux-symbols-4.8.22-r0-qemux86-64-20170622170129", 
              "file_path": "/tmp/linux9symbols", 
              "use_global_store": false
            }, 
            "thingDefKey": "hdc_device_manager_def"
          }, 
          "thingKey": "e8cdb5c5-c3f0-4820-8eef-7506c51b0676-device_manager_py"
        }
      ]
    }, 
    "success": true
  }
}
Nov 10 13:35:07 INFO: handler.py:643 - Received success for 0014-1 - Mailbox Check
Nov 10 13:35:07 INFO: device_manager.py:236 - Downloading
Nov 10 13:35:07 INFO: handler.py:1037 - Request download of vmlinux-symbols-4.8.22-r0-qemux86-64-20170622170129
Nov 10 13:35:07 INFO: handler.py:1176 - MQTT queued 0015-1 - Download vmlinux-symbols-4.8.22-r0-qemux86-64-20170622170129
{
  "command": "file.get", 
  "params": {
    "fileName": "vmlinux-symbols-4.8.22-r0-qemux86-64-20170622170129", 
    "global": false, 
    "thingKey": "e8cdb5c5-c3f0-4820-8eef-7506c51b0676-device_manager_py"
  }
}
Nov 10 13:35:07 DEBUG: handler.py:998 - MQTT sent 0015
Nov 10 13:35:07 DEBUG: handler.py:984 - Received message on topic "reply/0015"
{
  "1": {
    "params": {
      "crc32": 4177729458, 
      "fileId": "5a05f14f7902897fc46fe214", 
      "fileSize": 222259016
    }, 
    "success": true
  }
}
Nov 10 13:35:07 INFO: handler.py:643 - Received success for 0015-1 - Download vmlinux-symbols-4.8.22-r0-qemux86-64-20170622170129
Nov 10 13:35:07 INFO: handler.py:474 - Downloading "vmlinux-symbols-4.8.22-r0-qemux86-64-20170622170129"
Nov 10 13:36:07 INFO: handler.py:1176 - MQTT queued 0016-1 - Action Complete "file_download" result : 16(Timed Out) "Timed Out"
{
  "command": "mailbox.ack", 
  "params": {
    "errorCode": 16, 
    "errorMessage": "Timed Out", 
    "id": "5a05f14f74e9364b20408f48"
  }
}
Nov 10 13:36:07 DEBUG: handler.py:998 - MQTT sent 0016
Nov 10 13:36:07 DEBUG: handler.py:984 - Received message on topic "reply/0016"
{
  "1": {
    "success": true
  }
}
Nov 10 13:36:07 INFO: handler.py:643 - Received success for 0016-1 - Action Complete "file_download" result : 16(Timed Out) "Timed Out"
Nov 10 13:36:23 INFO: handler.py:525 - Successfully downloaded "vmlinux-symbols-4.8.22-r0-qemux86-64-20170622170129"

**Comment by jkeffer** [comment]
I tried increasing the value in iot.cfg to 120 seconds ( I assume it's seconds), and the device console no longer reports an error. The file is the correct size.

It seems that the device may be behaving correctly, but it's not clear if it is responding to the cloud in the right way. 

If it is, then it appears that the problem is in the cloud and it may be a known issue. 

Nov 10 14:35:11 DEBUG: handler.py:984 - Received message on topic "notify/mailbox_activity"
{
  "sessionId": "5a05ff2b34305555646c4254", 
  "thingKey": "e8cdb5c5-c3f0-4820-8eef-7506c51b0676-device_manager_py"
}
Nov 10 14:35:11 INFO: handler.py:615 - Recevied notification of mailbox activity
Nov 10 14:35:11 INFO: handler.py:1176 - MQTT queued 0002-1 - Mailbox Check
{
  "command": "mailbox.check", 
  "params": {
    "autoComplete": false
  }
}
Nov 10 14:35:11 DEBUG: handler.py:998 - MQTT sent 0002
Nov 10 14:35:11 DEBUG: handler.py:984 - Received message on topic "reply/0002"
{
  "1": {
    "params": {
      "messages": [
        {
          "command": "method.exec", 
          "expires": "2017-11-10T19:35:13.535Z", 
          "from": "julia.keffer@windriver.com", 
          "id": "5a05ff6274e9364b2041b9a0", 
          "params": {
            "method": "file_download", 
            "params": {
              "file_name": "vmlinux-symbols-4.8.22-r0-qemux86-64-20170622170129", 
              "file_path": "/tmp/linux9symbols", 
              "use_global_store": false
            }, 
            "thingDefKey": "hdc_device_manager_def"
          }, 
          "thingKey": "e8cdb5c5-c3f0-4820-8eef-7506c51b0676-device_manager_py"
        }
      ]
    }, 
    "success": true
  }
}
Nov 10 14:35:11 INFO: handler.py:643 - Received success for 0002-1 - Mailbox Check
Nov 10 14:35:11 INFO: device_manager.py:236 - Downloading
Nov 10 14:35:11 INFO: handler.py:1037 - Request download of vmlinux-symbols-4.8.22-r0-qemux86-64-20170622170129
Nov 10 14:35:11 INFO: handler.py:1176 - MQTT queued 0003-1 - Download vmlinux-symbols-4.8.22-r0-qemux86-64-20170622170129
{
  "command": "file.get", 
  "params": {
    "fileName": "vmlinux-symbols-4.8.22-r0-qemux86-64-20170622170129", 
    "global": false, 
    "thingKey": "e8cdb5c5-c3f0-4820-8eef-7506c51b0676-device_manager_py"
  }
}
Nov 10 14:35:11 DEBUG: handler.py:998 - MQTT sent 0003
Nov 10 14:35:11 DEBUG: handler.py:984 - Received message on topic "reply/0003"
{
  "1": {
    "params": {
      "crc32": 4177729458, 
      "fileId": "5a05ff627902897fc470d3dc", 
      "fileSize": 222259016
    }, 
    "success": true
  }
}
Nov 10 14:35:11 INFO: handler.py:643 - Received success for 0003-1 - Download vmlinux-symbols-4.8.22-r0-qemux86-64-20170622170129
Nov 10 14:35:11 INFO: handler.py:474 - Downloading "vmlinux-symbols-4.8.22-r0-qemux86-64-20170622170129"
Nov 10 14:37:02 INFO: handler.py:525 - Successfully downloaded "vmlinux-symbols-4.8.22-r0-qemux86-64-20170622170129"
Nov 10 14:37:02 INFO: handler.py:1176 - MQTT queued 0004-1 - Action Complete "file_download" result : 0(Success)
{
  "command": "mailbox.ack", 
  "params": {
    "errorCode": 0, 
    "errorMessage": "", 
    "id": "5a05ff6274e9364b2041b9a0"
  }
}
Nov 10 14:37:02 DEBUG: handler.py:998 - MQTT sent 0004
Nov 10 14:37:02 DEBUG: handler.py:984 - Received message on topic "reply/0004"
{
  "1": {
    "success": true
  }
}
Nov 10 14:37:02 INFO: handler.py:643 - Received success for 0004-1 - Action Complete "file_download" result : 0(Success)

**Comment by jkeffer** [comment]
Possibly the same root cause as #112.

**Comment by lcc755** [comment]
Seems to be fixable by changing the blocking option in the file_download command to False instead of True. Should it be a variable that's set in the cloud? Right now it is hard coded as True.

**Comment by lcc755** [comment]
I should add that having it set as True means that the cloud will wait for the action to complete.
