### ISSUE TITLE
Windows device-manager returns duplicate MAC address

### ISSUE THREAD

**Issue by mafoglia** [Wind-River/device-cloud-python#127]
I see the following on Windows 10 Home in command shell.  Same info is also visible on IoT Portal.
Nov 19 11:00:15 INFO: handler.py:648 - Received success for 0001-7 - Attribute Publish mac_address : "C0:18:85:5F:C6:9D; 12:18:85:5F:C6:9D; 12:18:85:5F:C6:9D"

Here is some info from "ipconfig /all"
...
Wireless LAN adapter Wi-Fi:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Dell Wireless 1502 802.11b|g|n
   Physical Address. . . . . . . . . : C0-18-85-5F-C6-9D
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   Physical Address. . . . . . . . . : 12-18-85-5F-C6-9D
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : attlocal.net
   Description . . . . . . . . . . . : Realtek PCIe GBE Family Controller
   Physical Address. . . . . . . . . : D4-BE-D9-CD-96-98
   DHCP Enabled. . . . . . . . . . . : Yes
...

This last one is not returned to the IoT Portal.

Also, should we return MACs having "Media disconnected"?

**Comment by tonym-wrs** [comment]
Which issue should we focus on here, that instead of 1 MAC address the set of all MAC addresses is returned in mac_address, or that in this case one MAC address was included mac_address twice?

**Comment by mafoglia** [comment]
I believe PaulB requested that all MACs be returned, so we should focus on returning the set of MAC addresses with no dupes.
