### ISSUE TITLE
validate_script.py is failing last two tests

### ISSUE THREAD

**Issue by mafoglia** [Wind-River/device-cloud-python#130]
Seeing this on Windows and Ubuntu:

method_exec failied for upload - FAIL
method_exec failied for download - FAIL
Nov 20 16:43:49 INFO: handler.py:375 - Disconnecting...
Nov 20 16:43:50 INFO: handler.py:976 - MQTT disconnected

Failed on the following:
method_exec upload
method_exec download
mfoglia@mfoglia-laptop:~/devi

**Comment by element-82** [comment]
Note: this could be collisions between several running validate_scripts.  This script is designed to work with 2 thing keys called from travis, one for py2 another for py3.  Each script starts by deleting the thing key.  If 3 are running, it will delete a potentially currently running app and you will see disconnected.

Running by hand on ubuntu works fine for me.  What is your device_id?

**Comment by mafoglia** [comment]
I just removed all of my apps completely and removed the device_id file too.  Then ran:
python ./validate_script.py.  I still get the same two errors.  I have added you to my ORG, which is SAN_DIEGO on hdcstg.

**Comment by element-82** [comment]
Hi Mike,
I confirmed that we did not support different orgs with the validate script.  I have a fix for that.  The other issue is that your thing def didn't have the new methods.  I updated your thing def and our admin tools to track the change.

Pb
