### ISSUE TITLE
setup-cloud-deps.py  prompt for org is misleading

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#135]
The prompt for the org is Org ID, but the correct value is the Org key. 

On the Developer page, there is an ID listed, but when I entered it, the script returned an error. Using the key worked.

Name WRPUBS
ID 5a1598f3153a992f355208b0

While this script is for internal use, you never know who will use it.

**Comment by tonym-wrs** [comment]
I think it should be the Org Key, see: Line 218 where org is used as the value for "key"

https://github.com/Wind-River/device-cloud-python/blob/1fb8935bd17c1a4d413717eadf818364a26fe1dc/share/admin-tools/setup-cloud-deps.py#L288

**Comment by element-82** [comment]
The org key is correct.  We have to look up the id from install to install.  The org key will be the same.

**Comment by element-82** [comment]
Just to clarify, the prompt text is incorrect.  It should say Org Key.
