### ISSUE TITLE
The -c option for the device_manager.py application doesn't work on Windows

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#150]
When it combines the path with the file specified by the -f option, it uses a forward slash instead of a backward slash.

c:\Users\svc-iottest\device_cloud>python device_manager.py -c c:\users\svc-iottest\device_cloud -f iot.connect.cfg
Cannot find c:\users\svc-iottest\device_cloud/iot.connect.cfg
Traceback (most recent call last):
  File "device_manager.py", line 471, in <module>
    client.initialize()
  File "C:\Users\svc-iottest\AppData\Local\Programs\Python\Python36\lib\site-packages\device_cloud\_core\client.py", line 109, in initialize
    raise IOError("Cannot find {}".format(self.config.config_file))
OSError: Cannot find c:\users\svc-iottest\device_cloud/iot.connect.cfg

**Comment by lcc755** [comment]
Did you mean to use "iot.connect.cfg"? I renamed the file and didn't have a problem.

+ python <<<<  .\device_manager.py -f iot.connect.cfg > output.txt 2>&1
Nov 28 10:30:47 DEBUG: handler.py:111 - CONFIG:
{
  "app_id": "device_manager_py", 
  "ca_bundle_file": "C:\\Python27\\lib\\site-packages\\certifi\\cacert.pem", 
  "cloud": {
    "host": "core-api.hdcstg.net", 
    "port": 8883, 
    "token": "17md19GUA0rJBcO7"
  }, 
  "config_dir": ".", 
  "config_file": "./iot.connect.cfg", 
  "device_id": "c7281ae5-8bc0-464b-9bc3-7c21aaee3b8e", 
  "keep_alive": 0, 
  "key": "c7281ae5-8bc0-464b-9bc3-7c21aaee3b8e-device_manager_py", 
  "loop_time": 1, 
  "proxy": {}, 
  "qos_level": 1, 
  "thread_count": 3, 
  "validate_cloud_cert": true
}
Nov 28 10:30:47 DEBUG: handler.py:890 - log_level set as DEBUG
Nov 28 10:30:47 INFO: handler.py:247 - Registered action "file_download" with function "file_download"
Nov 28 10:30:47 INFO: handler.py:247 - Registered action "file_upload" with function "file_upload"
Nov 28 10:30:47 INFO: handler.py:247 - Registered action "shutdown_device" with function "method_not_implemented"
Nov 28 10:30:47 INFO: handler.py:247 - Registered action "reboot_device" with function "method_not_implemented"
Nov 28 10:30:47 INFO: handler.py:247 - Registered action "remote-access" with function "remote_access"
Nov 28 10:30:47 INFO: handler.py:247 - Registered action "decommission_device" with function "device_decommission"
Nov 28 10:30:47 INFO: handler.py:247 - Registered action "software_update" with function "update_callback"
Nov 28 10:30:47 INFO: handler.py:247 - Registered action "reset_agent" with function "agent_reset"
Nov 28 10:30:47 INFO: handler.py:247 - Registered action "quit" with function "quit_me"
Nov 28 10:30:47 INFO: handler.py:325 - Connecting...
Nov 28 10:30:47 INFO: handler.py:975 - MQTT connected: Connection Accepted.

**Comment by jkeffer** [comment]
Looks like I had a typo in my command. Retried it with file name iot-connect.cfg as intended and it works.
