### ISSUE TITLE
Files and directories under the share directory are missing from the pypi installer for the Python repository

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#151]
When I install the agent from the Python repository, the /usr/local/share/device_cloud directory is missing all the files under the share directory in this GitHub repo. The missing files includes the service file examples, ota examples, etc.

I searched my entire machine and they aren't located anywhere else.

**Comment by jkeffer** [comment]
Missing from the share directory on Windows also.

**Comment by Dick-Cote** [comment]
Julia indicates this needs to be resolved in order to doc the pypi installer
