### ISSUE TITLE
Reset Agent Method on Linux when Agent is Installed from PyPI Repository Fails

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#155]
I started the device manager with the following command: ./device_manager.py -c /home/jkeffer1/config -f iot-connect.cfg

I was in the /usr/local/share/device_cloud directory because I installed the agent from the PyPI repository.

I ran the Reset Agent method and got the following output. It fails because it can't find the iot-connect.cfg file in the local directory. I didn't try the decommission method, but it might have the same problem.

Nov 29 14:33:44 DEBUG: handler.py:1003 - MQTT sent 0005
Nov 29 14:33:44 DEBUG: handler.py:989 - Received message on topic "reply/0005"
{
  "1": {
    "params": {
      "messages": [
        {
          "command": "method.exec", 
          "expires": "2017-11-29T19:33:51.344Z", 
          "from": "julia.keffer@windriver.com", 
          "id": "5a1f0b902cd1331431d5c682", 
          "params": {
            "method": "reset_agent", 
            "thingDefKey": "hdc_device_manager_def"
          }, 
          "thingKey": "a922a615-c68e-4620-a6bf-eb44be8fc949-device_manager_py"
        }
      ]
    }, 
    "success": true
  }
}
Nov 29 14:33:44 INFO: handler.py:648 - Received success for 0005-1 - Mailbox Check
Nov 29 14:33:44 INFO: handler.py:375 - Disconnecting...
Nov 29 14:33:44 INFO: handler.py:383 - Waiting for replies...
Cannot find ./iot-connect.cfg
Traceback (most recent call last):
  File "device_manager.py", line 471, in <module>
    client.initialize()
  File "/usr/local/lib/python2.7/dist-packages/device_cloud/_core/client.py", line 109, in initialize
    raise IOError("Cannot find {}".format(self.config.config_file))
IOError: Cannot find ./iot-connect.cfg

**Comment by element-82** [comment]
Reset does not know how you overrode the config file location.  If you want to support this work flow, copy the iot-connnect.cfg to the same dir as the device manager.  Otherwise you need to edit the code to say where the config is.

**Comment by jkeffer** [comment]
That defeats the purpose of the -c option!
