### ISSUE TITLE
Python Agent on Linux Returns Not Found When Attempting to Retrieve a Specific Directory

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#156]
In the file_path box in the Retrieve Files window, I specified /tmp/mytest, which is a directory that contains two files. The method returns not found. 

In my iot.cfg I have "upload_tar_file":true

This works as expected if I don't fill in the file_path box. It retrieves the contents of runtime/upload as a tar file. If I specify just a directory in the box, it also fails. I expected it to tar up the mytest directory under the runtime/upload directory.

Nov 29 14:39:02 DEBUG: handler.py:1003 - MQTT sent 0005
Nov 29 14:39:02 DEBUG: handler.py:989 - Received message on topic "reply/0005"
{
  "1": {
    "params": {
      "messages": [
        {
          "command": "method.exec", 
          "expires": "2017-11-29T19:39:09.002Z", 
          "from": "julia.keffer@windriver.com", 
          "id": "5a1f0cce2cd1331431d5c707", 
          "params": {
            "method": "file_upload", 
            "params": {
              "file_path": "/tmp/mytest", 
              "use_global_store": false
            }, 
            "thingDefKey": "hdc_device_manager_def"
          }, 
          "thingKey": "a922a615-c68e-4620-a6bf-eb44be8fc949-device_manager_py"
        }
      ]
    }, 
    "success": true
  }
}
Nov 29 14:39:02 INFO: handler.py:648 - Received success for 0005-1 - Mailbox Check
Nov 29 14:39:02 INFO: device_manager.py:295 - Uploading mytest
Nov 29 14:39:02 INFO: handler.py:1083 - Request upload of /tmp/mytest
Nov 29 14:39:02 ERROR: handler.py:1095 - Cannot find file /tmp/mytest. Upload cancelled.
Nov 29 14:39:02 INFO: handler.py:1181 - MQTT queued 0006-1 - Action Complete "file_upload" result : 12(Not Found) "Not Found"
{
  "command": "mailbox.ack", 
  "params": {
    "errorCode": 12, 
    "errorMessage": "Not Found", 
    "id": "5a1f0cce2cd1331431d5c707"
  }
}
Nov 29 14:39:02 DEBUG: handler.py:1003 - MQTT sent 0006
Nov 29 14:39:02 DEBUG: handler.py:989 - Received message on topic "reply/0006"
{
  "1": {
    "success": true
  }
}
Nov 29 14:39:02 INFO: handler.py:648 - Received success for 0006-1 - Action Complete "file_upload" result : 12(Not Found) "Not Found"

**Comment by element-82** [comment]
Confirmed.
