### ISSUE TITLE
execution of method "reboot device" , module device_cloud in osal.py will fail due to wrong time format

### ISSUE THREAD

**Issue by hanse-windriver** [Wind-River/device-cloud-python#159]
Executing a reboot_device on Linux seems to add an illegal time format "+1now" for the shutdown command.
_shutdown -r +1now_ 

seems to be a  result of below code i **osal.py**

line 105-108 in osal.py (system_shutdown)
```
if POSIX:
        command = "sudo /sbin/shutdown "
        command += "-r +1" if reboot else "-h "
        command += "now " if delay == 0 else "+{} ".format(delay)
```
removing +1 (keep a seperator space) makes it work.
```
if POSIX:
        command = "sudo /sbin/shutdown "
        command += "-r " if reboot else "-h "
        command += "now " if delay == 0 else "+{} ".format(delay)
```

**Comment by element-82** [comment]
The goal of the +1 is to return a result with enough time to have it reach the cloud before tearing down.  However, the +1 is the default on most systems.  It think it is safe to remove it.

**Comment by hanse-windriver** [comment]
I think the main problem is that the python code merges  both strings "+1" and "now" into one time format string, i.e. "+1now", if "reboot" was true.
