### ISSUE TITLE
README instruction for install are incomplete

### ISSUE THREAD

**Issue by captaingoodnight** [Wind-River/device-cloud-python#160]
OS: Raspbian

The instructions in the README say to run `pip install .`  after checkout. This fails with during the cleanup step due to a permission problem. 

You must run `sudo pip install .` for the install to execute correctly.

**Comment by ccassidy-wrs** [comment]
Also, if older versions of the python packages are already installed on the system, the required version e.g paho-mqtt 1.3.1 may not be installed unless you use "pip install . --upgrade".
