### ISSUE TITLE
Enhancements to improve the user's initial experience with the product

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#166]
The goal of the quick start is to get the device manager thing and telemetry app thing connected to the cloud and transmitting telemetry. It would improve the quick start procedure if we can add a topic to show how to create a basic trigger based on telemetry. The following enhancements are required:

- Move all the applications and associated configuration files (including iot.cfg) to the same directory and rename it apps. This enables the user to generate all configuration files in the same directory and run the applications from the same directory without specifying paths on the command line. The device_id file will be created in a common place and all applications will have the same value in their thing key, which enables the user to easily identify their things on the Management Portal.

- In the telemetry thing def, add an alarm to the telemetry app that a trigger can update. To avoid confusion with the current alarm and improve clarity, change the name of alarm_1 to telemetry_alarm and change the state text to on and off. Update the telemetry app to match.

**Comment by element-82** [comment]
We are not planning on moving the demo apps to the top level.  This will create a mess in the top level directory.  The idea is to have the demos all contained to a demo directory.

I think the the alarm state idea makes sense, e.g. to make it more trigger friendly and make the alarm actually do something useful.

**Comment by jkeffer** [comment]
Guess I wasn't clear. I would like all the apps, including the demo apps, the device manager app, and any other apps as you see fit into a single, separate directory, not at the top level.
