### ISSUE TITLE
Support Completion Variables for Actions

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#167]
The APIs should support returning completion variables for methods. Completion variables are the only valid way for an application to return information about a successful result. Success details are useful in the method output box or for use in a trigger. 

For example, the simple telemetry sample app uses the status message to return "Turned On" in the output box. This message is only intended for error messages and this is not the correct way to produce this output. Successful results should use only an empty string in the message. If I create a trigger that starts telemetry when a new telemetry app thing is created, it goes through the failure route on the method.exec action and it looks like the trigger failed.

**Comment by Dick-Cote** [comment]
Bug Board - Need RCA on where the source of the problem is

**Comment by element-82** [comment]
Julia,
do you mean out parameters?  E.g. the device receives an action with params, one of them is intended for output.  

Re: The telemetry example app: it  adds a helpful string, but that is not the correct way, agreed.  That is deemed a failure in the cloud.

**Comment by jkeffer** [comment]
Yes, completion variables defined for the method in the thing definition represent output parameters for the function that implements the method. I don't know if the device receives that action with params as such, but it is the same principle. Take a look at the C API and how it implements the parameter type IOT_PARAMETER_OUT in the actions API.

**Comment by element-82** [comment]
Yes, I know about the Clib out params.  In fact, now that I look, python supports them too.  E.g. in a test case callback:
```
def parameter_action(client, params):
    """
    Action callback that takes two parameters, client and action params, that
    will print the message present in the "message" parameter send by the cloud
    when the action is executed.
    """
    message = params.get("message", "")
    print(message)

    p = {}
    p['response_txt'] = "this is response output"

    return (iot.STATUS_SUCCESS, "", p)
```

I can add an example on how to use to a demo app, but I wanted to point out that it is supported by the python API.
