### ISSUE TITLE
Initial connect of device_manager.py should retry if no network connection is available

### ISSUE THREAD

**Issue by jito-wrs** [Wind-River/device-cloud-python#169]
Currently if there is no network connection available when the device_manager.py is run, the cloud connection fails and then the .py file exits. Ideally the two disconnection conditions (disconnect happens after initial connection and when the script starts the cloud is not reachable) should be dealt with in the same way.

i.e. after creating the client instance and initializing it, the script should be able to continue without waiting or requiring the client to be effectively connected. Then, when the connection is made (after as many retries as needed), the main script would be notified by some callback so that it can start sending metrics and everything else.

**Comment by element-82** [comment]
The normal way to handle daemons is with a monitor like systemd or a windows service, where the service will restart the daemon if it exits.  For convenience, I can add a network check loop before connecting.  It will not affect systemd users.

**Comment by Dick-Cote** [comment]
Bug Board Reviewed
