### ISSUE TITLE
telemetry_publish does not seem to support timestamp

### ISSUE THREAD

**Issue by jito-wrs** [Wind-River/device-cloud-python#171]
Looking at the pydoc output for device_cloud, indicates that there is a timestamp available in the method but there is no indication of how it should be used and if some standard formats are tried, they are disregarded in the data that is seen in the Thing.

**Comment by element-82** [comment]
Hi Jennifer,
it is supported but not documented.   Here is how to use it:

```
from datetime import datetime
datetime(2002, 12, 25,11,34,22,11)
client.telemetry_publish(p, value, cloud_response, timestamp=ts)
```
This will send e.g. timestamps for 2002.

The  iot-simple-telemetry.py app will be updated and so will the documentation.
