### ISSUE TITLE
iot-simple-telemetry sample app fails to read properties and attributes the first three times it runs

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#179]
The first time I run the application as a new thing, it produces an error when it tries to read the first property and attribute sent to the cloud. I have to run the application four times and start telemetry before it runs without errors. When I get the errors, neither the Quit App action or CTRL-C on the command line stop the program. I have to kill -9. 

The output below shows the error output from each of the first three times I run it.

This is the output the first time I run it:

Feb 01 13:37:36 INFO: iot-simple-telemetry.py:142 - Publishing Property: 310.01 to property-1
Feb 01 13:37:36 INFO: handler.py:1307 - MQTT queued 0004-1 - Reading current property...
{
  "command": "property.current", 
  "params": {
    "key": "property-1", 
    "thingKey": "a3738269-b048-4bb4-88a0-779974ec9103-iot-simple-telemetry-py"
  }
}
Feb 01 13:37:36 INFO: handler.py:1307 - MQTT queued 0005-1 - Property Publish property-1 : 310.01
{
  "command": "property.publish", 
  "params": {
    "key": "property-1", 
    "thingKey": "a3738269-b048-4bb4-88a0-779974ec9103-iot-simple-telemetry-py", 
    "ts": "2018-02-01T13:37:36.222568Z", 
    "value": 310.01
  }
}
Feb 01 13:37:36 DEBUG: handler.py:1100 - MQTT sent 0004
Feb 01 13:37:36 DEBUG: handler.py:1087 - Received message on topic "reply/0004"
{
  "1": {
    "errorCodes": [
      -92508
    ], 
    "errorMessages": [
      "Property 'property-1' is not set for specified Thing."
    ], 
    "success": false
  }
}
Feb 01 13:37:36 DEBUG: handler.py:1100 - MQTT sent 0005
Feb 01 13:37:36 DEBUG: handler.py:1087 - Received message on topic "reply/0005"
{
  "1": {
    "success": true
  }
}
Feb 01 13:37:36 ERROR: handler.py:695 - Received failure for 0004-1 - Reading current property...
Feb 01 13:37:36 ERROR: handler.py:696 - .... {u'errorCodes': [-92508], u'errorMessages': [u"Property 'property-1' is not set for specified Thing."], u'success': False}
Feb 01 13:37:36 ERROR: handler.py:905 - Exception:
Traceback (most recent call last):
  File "/home/jkeffer/dc_feb1/local/lib/python2.7/site-packages/device_cloud/_core/handler.py", line 894, in handle_work_loop
    self.handle_message(work.data)
  File "/home/jkeffer/dc_feb1/local/lib/python2.7/site-packages/device_cloud/_core/handler.py", line 785, in handle_message
    sent_message.data.status = constants.STATUS_FAILURE
AttributeError: 'NoneType' object has no attribute 'status'
Feb 01 13:37:36 INFO: handler.py:692 - Received success for 0005-1 - Property Publish property-1 : 310.01
Traceback (most recent call last):
  File "./iot-simple-telemetry.py", line 150, in <module>
    status, rvalue, timestamp = client.telemetry_read_last_sample(p)
  File "/home/jkeffer/dc_feb1/local/lib/python2.7/site-packages/device_cloud/_core/client.py", line 534, in telemetry_read_last_sample
    return self.handler.handle_telemetry_get(telemetry_name)
  File "/home/jkeffer/dc_feb1/local/lib/python2.7/site-packages/device_cloud/_core/handler.py", line 949, in handle_telemetry_get
    value = self.response['telemetry_current_value']
KeyError: 'telemetry_current_value'

This is the output after I run it a second time:

Feb 01 13:38:57 INFO: iot-simple-telemetry.py:142 - Publishing Property: 554.76 to property-2
Feb 01 13:38:57 INFO: handler.py:1307 - MQTT queued 0007-1 - Reading current property...
{
  "command": "property.current", 
  "params": {
    "key": "property-2", 
    "thingKey": "a3738269-b048-4bb4-88a0-779974ec9103-iot-simple-telemetry-py"
  }
}
Feb 01 13:38:57 INFO: handler.py:1307 - MQTT queued 0008-1 - Property Publish property-2 : 554.76
{
  "command": "property.publish", 
  "params": {
    "key": "property-2", 
    "thingKey": "a3738269-b048-4bb4-88a0-779974ec9103-iot-simple-telemetry-py", 
    "ts": "2018-02-01T13:38:57.263221Z", 
    "value": 554.76
  }
}
Feb 01 13:38:57 DEBUG: handler.py:1100 - MQTT sent 0007
Feb 01 13:38:57 DEBUG: handler.py:1087 - Received message on topic "reply/0007"
{
  "1": {
    "errorCodes": [
      -92508
    ], 
    "errorMessages": [
      "Property 'property-2' is not set for specified Thing."
    ], 
    "success": false
  }
}
Feb 01 13:38:57 ERROR: handler.py:695 - Received failure for 0007-1 - Reading current property...
Feb 01 13:38:57 ERROR: handler.py:696 - .... {u'errorCodes': [-92508], u'errorMessages': [u"Property 'property-2' is not set for specified Thing."], u'success': False}
Feb 01 13:38:57 ERROR: handler.py:905 - Exception:
Traceback (most recent call last):
  File "/home/jkeffer/dc_feb1/local/lib/python2.7/site-packages/device_cloud/_core/handler.py", line 894, in handle_work_loop
    self.handle_message(work.data)
  File "/home/jkeffer/dc_feb1/local/lib/python2.7/site-packages/device_cloud/_core/handler.py", line 785, in handle_message
    sent_message.data.status = constants.STATUS_FAILURE
AttributeError: 'NoneType' object has no attribute 'status'
Feb 01 13:38:57 DEBUG: handler.py:1100 - MQTT sent 0008
Feb 01 13:38:57 DEBUG: handler.py:1087 - Received message on topic "reply/0008"
{
  "1": {
    "success": true
  }
}
Feb 01 13:38:57 INFO: handler.py:692 - Received success for 0008-1 - Property Publish property-2 : 554.76
Feb 01 13:38:58 INFO: handler.py:1307 - MQTT queued 0009-1 - Reading current property...
{
  "command": "property.current", 
  "params": {
    "key": "property-2", 
    "thingKey": "a3738269-b048-4bb4-88a0-779974ec9103-iot-simple-telemetry-py"
  }
}
Feb 01 13:38:58 DEBUG: handler.py:1100 - MQTT sent 0009
Feb 01 13:38:58 DEBUG: handler.py:1087 - Received message on topic "reply/0009"
{
  "1": {
    "params": {
      "ts": "2018-02-01T13:38:57.263Z", 
      "value": 554.76
    }, 
    "success": true
  }
}
Feb 01 13:38:58 INFO: handler.py:692 - Received success for 0009-1 - Reading current property...
Feb 01 13:38:59 INFO: iot-simple-telemetry.py:160 - Property read back from cloud:
	name property-2
	status 0
	value 554.76
	timestamp 2018-02-01T13:38:57.263Z

Feb 01 13:38:59 INFO: iot-simple-telemetry.py:173 - Publishing Attribute: mcyshdwnowfnbbtitndq to attribute-1
Feb 01 13:38:59 INFO: handler.py:1307 - MQTT queued 0010-1 - Reading current attribute...
{
  "command": "attribute.current", 
  "params": {
    "key": "attribute-1", 
    "thingKey": "a3738269-b048-4bb4-88a0-779974ec9103-iot-simple-telemetry-py"
  }
}
Feb 01 13:38:59 INFO: handler.py:1307 - MQTT queued 0011-1 - Attribute Publish attribute-1 : "mcyshdwnowfnbbtitndq"
{
  "command": "attribute.publish", 
  "params": {
    "key": "attribute-1", 
    "thingKey": "a3738269-b048-4bb4-88a0-779974ec9103-iot-simple-telemetry-py", 
    "ts": "2018-02-01T18:38:59.270431Z", 
    "value": "mcyshdwnowfnbbtitndq"
  }
}
Feb 01 13:38:59 DEBUG: handler.py:1100 - MQTT sent 0010
Feb 01 13:38:59 DEBUG: handler.py:1087 - Received message on topic "reply/0010"
{
  "1": {
    "errorCodes": [
      -93002
    ], 
    "errorMessages": [
      "Attribute 'attribute-1' is not set for specified Thing."
    ], 
    "success": false
  }
}
Feb 01 13:38:59 ERROR: handler.py:695 - Received failure for 0010-1 - Reading current attribute...
Feb 01 13:38:59 ERROR: handler.py:696 - .... {u'errorCodandes': [-93002], u'errorMessages': [u"Attribute 'attribute-1' is not set for specified Thing."], u'success': False}
Feb 01 13:38:59 ERROR: handler.py:905 - Exception:
Traceback (most recent call last):
  File "/home/jkeffer/dc_feb1/local/lib/python2.7/site-packages/device_cloud/_core/handler.py", line 894, in handle_work_loop
    self.handle_message(work.data)
  File "/home/jkeffer/dc_feb1/local/lib/python2.7/site-packages/device_cloud/_core/handler.py", line 796, in handle_message
    sent_message.data.status = constants.STATUS_FAILURE
AttributeError: 'NoneType' object has no attribute 'status'
Feb 01 13:38:59 DEBUG: handler.py:1100 - MQTT sent 0011
Feb 01 13:38:59 DEBUG: handler.py:1087 - Received message on topic "reply/0011"
{
  "1": {
    "success": true
  }
}
Feb 01 13:38:59 INFO: handler.py:692 - Received success for 0011-1 - Attribute Publish attribute-1 : "mcyshdwnowfnbbtitndq"
Traceback (most recent call last):
  File "./iot-simple-telemetry.py", line 176, in <module>
    status, rvalue, timestamp = client.attribute_read_last_sample(a)
  File "/home/jkeffer/dc_feb1/local/lib/python2.7/site-packages/device_cloud/_core/client.py", line 549, in attribute_read_last_sample
    return self.handler.handle_attribute_get(attribute_name)
  File "/home/jkeffer/dc_feb1/local/lib/python2.7/site-packages/device_cloud/_core/handler.py", line 506, in handle_attribute_get
    value = self.response['attribute_current_value']
KeyError: 'attribute_current_value'

I see this in the output when I run it a third time: 

Feb 01 13:41:25 INFO: handler.py:1307 - MQTT queued 0014-1 - Attribute Publish attribute-2 : "kwsyfbfsutpeoknaizjy"
{
  "command": "attribute.publish", 
  "params": {
    "key": "attribute-2", 
    "thingKey": "a3738269-b048-4bb4-88a0-779974ec9103-iot-simple-telemetry-py", 
    "ts": "2018-02-01T18:41:25.262033Z", 
    "value": "kwsyfbfsutpeoknaizjy"
  }
}
Feb 01 13:41:25 DEBUG: handler.py:1100 - MQTT sent 0013
Feb 01 13:41:25 DEBUG: handler.py:1087 - Received message on topic "reply/0013"
{
  "1": {
    "errorCodes": [
      -93002
    ], 
    "errorMessages": [
      "Attribute 'attribute-2' is not set for specified Thing."
    ], 
    "success": false
  }
}
Feb 01 13:41:25 ERROR: handler.py:695 - Received failure for 0013-1 - Reading current attribute...
Feb 01 13:41:25 ERROR: handler.py:696 - .... {u'errorCodes': [-93002], u'errorMessages': [u"Attribute 'attribute-2' is not set for specified Thing."], u'success': False}
Feb 01 13:41:25 ERROR: handler.py:905 - Exception:
Traceback (most recent call last):
  File "/home/jkeffer/dc_feb1/local/lib/python2.7/site-packages/device_cloud/_core/handler.py", line 894, in handle_work_loop
    self.handle_message(work.data)
  File "/home/jkeffer/dc_feb1/local/lib/python2.7/site-packages/device_cloud/_core/handler.py", line 796, in handle_message
    sent_message.data.status = constants.STATUS_FAILURE
AttributeError: 'NoneType' object has no attribute 'status'

**Comment by jkeffer** [comment]
I believe there is a race condition, because if I set cloud_response to true for the telemetry_publish function, the telemetry read works the first time. There is no parameter to wait for the response for the attribute_publish function, so I still see the errors from the code that attempts to read the first attribute value published when I run the program the first time.

**Comment by element-82** [comment]
There are some unhandled exceptions in the code.  We are probably seeing this now because the hdcstg.net cloud is very slow right now.  I will add code to handle the exceptions.

**Comment by jkeffer** [comment]
I've seen this on other days as well, not just today.
