### ISSUE TITLE
Uploaded files are deleted regardless of "upload_remove_on_success" setting

### ISSUE THREAD

**Issue by ccassidy-wrs** [Wind-River/device-cloud-python#209]
When I modify iot.cfg and set "upload_remove_on_success" to false (and restart device manager), uploaded files are still deleted from the runtime upload directory. 

Does this behaviour depend on the source dir of the uploaded files?

**Comment by jkeffer** [comment]
This setting applies only if you retrieve files from the runtime_dir/upload directory, where the runtime_dir is set in the same file.

**Comment by ccassidy-wrs** [comment]
Yes my file is located in <runtime dir>/upload and is still being deleted, regardless of setting.
