### ISSUE TITLE
Setting "wait_for_file_transfer" to false breaks file upload

### ISSUE THREAD

**Issue by ccassidy-wrs** [Wind-River/device-cloud-python#211]
If you set "wait_for_file_transfer" to false in iot.cfg for a non-blocking transfer, a file upload operation fails as the file cannot be found (see attached log), even though it is present in the specified directory (runtime/upload).

The same test works on the same device when "wait_for_file_transfer" is set to true.

Is the file being deleted before the non-blocking operation completes?

[upload_log.txt](https://github.com/Wind-River/device-cloud-python/files/1802980/upload_log.txt)

**Comment by element-82** [comment]
Chris,
if you set wait to false, the API will return right away and since the file is not there, it will look like a failure.  Meanwhile, the API is doing the file xfer asynchronously.  You need to add a poll loop for the file.
