### ISSUE TITLE
Not a bug: relay.py closes websocket during RDP session

### ISSUE THREAD

**Issue by bush** [Wind-River/device-cloud-python#220]
If I configure a remote access connection and setup an RDP session between a windows 10 client and a device running windows 10 the RDP session is closed after 1 minute of inactivity.  The device_manager displays the following error message:

Mar 15 18:59:21 INFO: handler.py:777 - Received success for 0023-1 - Action Complete "remote-access" result : 0(Success)
Mar 15 19:30:07 INFO: relay.py:120 - Relay:127.0.0.1:3389(43285) - Received NULL from websocket, Stopping
Mar 15 19:30:07 INFO: relay.py:138 - Relay:127.0.0.1:3389(43285) - Sockets Closed

**Comment by element-82** [comment]
Dave,
I removed the code that handles the null from the WS side and the connection still drops.  Now there is no indication on the python log that anything is wrong.  So, I don't think the relay.py class is the cause.  We need to see what is going on between the rdp client and the micro service.  I think the microservice side down to the device WS is still up and the rdp client side is down.

**Comment by bush** [comment]
Ok thanks Paul.  I will continue to investigate.
