### ISSUE TITLE
Add flag to indicate rollback performed

### ISSUE THREAD

**Issue by ccassidy-wrs** [Wind-River/device-cloud-python#232]
For IDP, we have custom initramfs code to perform rollback. Once rollback is complete, there is no indicator in the booted system that a rollback has been performed. 

Can we set a flag in /var/lib/python-device-cloud to indicate rollback complete. Users can then check for this (e.g. in a modified device manager) and set an alarm if necessary.

**Comment by element-82** [comment]
This change will be made in the lvmcheck script that lives in the meta-device-cloud.

**Comment by element-82** [comment]
This bug was fixed by f7c43d03f3e40f324f33d4536a90c2d2a677a5c5 in meta-device-cloud.
