### ISSUE TITLE
Validate applications are missing from the PyPI installer

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#238]
The validate*.py applications do not get installed if the user installs the agent using pip.

**Comment by Dick-Cote** [comment]
Validation Scripts can come from Git Repository for users that need it

**Comment by mafoglia** [comment]
Second request for these scripts to be present when installing via pip.  Reason:  Work is being done on a HW validation procedure.  To keep things simple, the procedure currently uses pip as install mechanism.  It is onerous to ask the person running the validation to go grab extra files.
