### ISSUE TITLE
building meta-device-cloud layer for IDP with HDC 2.x fails 

### ISSUE THREAD

**Issue by alyneho** [Wind-River/device-cloud-python#244]
Building meta-device-cloud layer for IDP with HDC 2.x fails. These two version of HDC cause a build error indicating both packages conflict due to duplicate files provided by each version.  See HDCNEXT-336.

**Comment by element-82** [comment]
The fix was pushed to meta-device-cloud and device-cloud-python.  However, the meta build uses the latest release.  Once device-cloud-python is fully tested, I will push to pypi and update the reference in meta-device-cloud.

**Comment by element-82** [comment]
e78ade0dffa72b3dbe7c68de0982753ec711d700 was pushed to meta-device-cloud to track 18.04.18
