### ISSUE TITLE
Error caused when trying to Remote-Access in automation

### ISSUE THREAD

**Issue by rhage1118** [Wind-River/device-cloud-python#255]
Seeing an error when running automation to create_remoteaccess:

(Error in message_ids: see stack_trace below):
-------------------------------------------------

ack_messages path runtime/message_ids
Traceback (most recent call last):
 File "../../device-cloud-python/device_manager.py", line 649, in <module>
   ack_messages(client, os.path.join(runtime_dir, "message_ids"))
 File "../../device-cloud-python/device_manager.py", line 72, in ack_messages
   id, status = msg_id.split(',')
ValueError: too many values to unpack
(Python 2.7.12)

**Comment by element-82** [comment]
Fixed in b2ef3f84bd63aaf06a0d972de0cffceaf3bdc7a7
