### ISSUE TITLE
Agent should have some error handling concerning API maximum limits

### ISSUE THREAD

**Issue by jito-wrs** [Wind-River/device-cloud-python#256]
It would be good if the agent was able to avoid ignoring API limit being reached and calls continuing to be sent on the org where the limit has been reached.

If this is not available in the agent itself, it would be nice if the demos had examples of how to handle error responses and it was mentioned explicitly in the docs that API responses should not be ignored.

**Comment by element-82** [comment]
There are a number of ways this can be mitigated:
  * application must be fixed not to flood the cloud
  * cloud can take defensive action and black list offending device
  * API instance can silence itself with a flag and stop sending for a time interval.  Once the interval has passed, the flag is cleared and sending as usual

**Comment by karthikprabhu17** [comment]
Any idea when will this be available in pypy? The latest is 18.04.18 and updated April 18th

**Comment by jito-wrs** [comment]
The release cadence for PyPi is usually monthly or if there is a fix that is particularly needed.
