### ISSUE TITLE
Python 2.7 proxy setup - Get errro on PySocks

### ISSUE THREAD

**Issue by bmalhi** [Wind-River/device-cloud-python#257]
Unable to get python agent running via proxy on Windows using python 2.7.14.
To resolve issue PySocks need updating on Python 2.7, 
Note: Issue not seen in Python 3

--- Info to resolve ---
 $ python --version
Python 2.7.14
> pip install --upgrade PySocks

**Comment by element-82** [comment]
This was fixed in 8c4d6315f2dc6df9355f51c9ca262399adc23f3f.
