### ISSUE TITLE
On Windows, unable to Device console, and Remote Access to device running through proxy

### ISSUE THREAD

**Issue by bmalhi** [Wind-River/device-cloud-python#261]
--- Environment ---
OS: Windows 10 Enterprise 64bit
HDC2Next Version: 18.15.0321
HDC2Next URL: https://preview.hdcstg.net

--- Actual ---
- On Launchpad just get spinning wheel when attempting to connect to the device running via proxy
- Note: Issue is not seen on Ubuntu 16:04

--- Expected ---
- Get login prompt for ssh/telnet

--- Reproduce Issue ---
0. Device (python 2 or Python 3) is running through proxy
1. On launchpad click on Device console, or Remote Access app
2. Attempt to connect to device

**Comment by element-82** [comment]
There is a bug in the websocket-client library.  PR sent, waiting for feedback:
https://github.com/websocket-client/websocket-client/pull/427
