### ISSUE TITLE
File transfers is not working when not using the default port

### ISSUE THREAD

**Issue by ytianwr** [Wind-River/device-cloud-python#262]
The python agent needs a way to set port number for file transfer.
My environment uses port 8443 for file transfer, I have to make the following change to make the file upload/download work:
diff --git a/device_cloud/_core/handler.py b/device_cloud/_core/handler.py
index 6c4befd..ef9654c 100755
--- a/device_cloud/_core/handler.py
+++ b/device_cloud/_core/handler.py
@@ -650,7 +650,7 @@ class Handler(object):
         status = constants.STATUS_SUCCESS
         self.logger.info("Downloading \"%s\"", file_xfer_obj.file_name)
         self.logger.info("File size \"%d\"", file_xfer_obj.file_size)
-        url = "https://{}/file/{}".format(self.config.cloud.host, file_xfer_obj.file_id)
+        url = "https://{}:{}/file/{}".format(self.config.cloud.host, 8443, file_xfer_obj.file_id)
         download_dir = os.path.dirname(file_xfer_obj.file_path)
         temp_file_name = "".join([random.choice("0123456789") for _ in range(10)])
         temp_file_name += ".part"
@@ -702,7 +702,7 @@ class Handler(object):
                          os.path.basename(upload.file_path), upload.file_name)
 
         # Start creating URL for file upload
-        url = "https://{}/file/{}".format(self.config.cloud.host,
+        url = "https://{}:{}/file/{}".format(self.config.cloud.host, 8443,
                                           upload.file_id)
 
         response = None

**Comment by element-82** [comment]
Is the REST port on your on prem setup 8443 as well?
