### ISSUE TITLE
Remote-Access causes error in stdout

### ISSUE THREAD

**Issue by rhage1118** [Wind-River/device-cloud-python#283]
Error is below, as follows:
error from callback <bound method Relay._on_error of <device_cloud.relay.Relay object at 0x7fbe03a57a20>>: cannot join current thread

Steps - Full TEST code below (Python3 virtualenv) 
1) call API for create endpoint remote_access
2) create a Websocket and send the 'CONNECTED-129812'
3) close websocket 
Note:  No DATA in pipe is sent or received.

Device-Manager logs:
-----------------------
{
  "1": {
    "params": {
      "messages": [
        {
          "command": "method.exec",
          "expires": "2018-06-12T19:21:06.682Z",
          "from": "ramsey.hage@windriver.com",
          "id": "5b201ce674e936578798b3d3",
          "params": {
            "method": "remote-access",
            "params": {
              "host": "localhost",
              "protocol": "46811",
              "reconnect": false,
              "url": "wss://integration.hdcdevel.net/ws/hdc/remote-access/01360a50b4a9/6e6a1632-5444-4b7e-a52a-862707e30084?jwt=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1Mjg4MzEyMDcsIm5iZiI6MTUyODgyNzYwNywiZXhwIjoxNTI4OTE3NjA3LCJpc3MiOiJoZGNkZXZlbC5uZXQiLCJzdWIiOiJyYW1zZXkuaGFnZUB3aW5kcml2ZXIuY29tIiwib3JnYW5pemF0aW9uIjoiVEVTVCIsInRoaW5nIjoicHl0aG9uM19yaGFnZV92bV9kZXZtZ3JfcHktZGV2aWNlX21hbmFnZXJfcHkiLCJlbmRwb2ludCI6Ijk3N2IyM2Y2LTQ4YWMtNDJiNi04OWM1LTQ1Y2Y4YThkYWZhYiIsInBlcm1pc3Npb24iOnsiV2ViU29ja2V0RW5kcG9pbnQiOnRydWV9fQ.CyzyKcukJX2n-09lo4ncbXuG3lCNEvrbmCLrZpSIs183rlZbgt7xKhRE_Fn7USsNBtXDp8L0iF8QRbcgENpjC-V6pLryah4BUrFiYZItbM5xvJCqEz8cQzwbmLkJxYt9mddWNIkTDrHbAAyY6N8GANR6PWjjw-GcPxHmvGRPBptqASU1e5L8JJPwdj1Sxv7r1UViSl-JksMJnE4lljtL8cbA6rVpiLhhLs8LMGmVNqi90Qy0sr1ybM1F7t-QEOyL4JvlKT_brx5QS1YjIB7GlY7KKlMsjTZopAxlAyMUYKHIl0U6q0_OeyvgKrdYQfu-EZ1PUGToG5ZtiqQJsUGhPQ"
            },
            "thingDefKey": "hdc_device_manager_def"
          },
          "thingKey": "python3_rhage_vm_devmgr_py-device_manager_py"
        }
      ]
    },
    "success": true
  }
}
Jun 12 15:19:33 INFO: handler.py:832 - Received success for 0002-1 - Mailbox Check
Port 46811 listening
Jun 12 15:19:33 INFO: handler.py:1569 - MQTT queued 0003-1 - Action Complete "remote-access" result : 0(Success)
{
  "command": "mailbox.ack",
  "params": {
    "errorCode": 0,
    "errorMessage": "",
    "id": "5b201ce674e936578798b3d3"
  }
}
Jun 12 15:19:33 DEBUG: handler.py:1357 - MQTT sent 0003
Jun 12 15:19:33 DEBUG: handler.py:1344 - Received message on topic "reply/0003"
{
  "1": {
    "success": true
  }
}
Jun 12 15:19:33 INFO: handler.py:832 - Received success for 0003-1 - Action Complete "remote-access" result : 0(Success)
Jun 12 15:19:33 INFO: relay.py:220 - _on_open: starting thread loop
Jun 12 15:19:33 DEBUG: relay.py:94 - _connect_local idx 0
Jun 12 15:19:33 DEBUG: relay.py:113 - connected to 46811.
Jun 12 15:19:33 DEBUG: relay.py:239 - Relay:localhost:46811(40765) Local socket opened
Jun 12 15:19:49 INFO: relay.py:271 - _on_close: websocket closed
Closing sock 0
Jun 12 15:19:49 ERROR: relay.py:264 - _on_error: 'NoneType' object has no attribute 'connected'
Jun 12 15:19:49 INFO: relay.py:271 - _on_close: websocket closed
Jun 12 15:19:49 INFO: relay.py:310 - Relay:localhost:46811(40765) Stopping
Jun 12 15:19:49 INFO: relay.py:217 - Relay:localhost:46811(40765) - Sockets Closed
error from callback <bound method Relay._on_error of <device_cloud.relay.Relay object at 0x7fbe03a57a20>>: cannot join current thread

TEST Code for this Issue:
---------------------------
import ssl
import websocket
from cloud.api.HdcAPI import HdcAPI
obj = HdcAPI()
obj._get_org()
thingKey_devicemgr = "python3_rhage_vm_devmgr_py-device_manager_py"
endpointName = 'test_basic_flow_endpoint'
IP, PORT = "localhost", 46811
endpoint = obj.create_remoteaccess(thingKey_devicemgr, endpointName, host=IP, protocol=PORT) 
endpointInfo = endpoint['json']
wsUrl = endpointInfo['url'].encode('utf-8').decode()
wsJwt = endpointInfo['jwt'].encode('utf-8').decode()
uri = wsUrl + '?jwt=' + wsJwt
uri
sslopt = {"cert_reqs": ssl.CERT_NONE}
wsocket = websocket.WebSocket(sslopt=sslopt)
wsocket.connect(uri)
wsocket.send('CONNECTED-129812')
wsocket.connected
if wsocket.connected:
    wsocket.close()

TCP Server:
------------
import socket
import threading
import socketserver
class ThreadedTCPServer(socketserver.ThreadingMixIn, socketserver.TCPServer):
    pass

class MyTCPHandler(socketserver.StreamRequestHandler):
    def handle(self):
        print('In tcp server handle')
        self.data = self.rfile.readline().strip()
        print("{} wrote: {}".format(self.client_address[0], self.data))
        upperData = self.data.upper()
        self.wfile.write(upperData)
        print('sent back uppercase: {}'.format(str(upperData)))
        self.rfile.readline().strip()

server = ThreadedTCPServer(('localhost',0), MyTCPHandler)                    
                                                                                 
server_thread = threading.Thread(target=server.serve_forever)                
server_thread.daemon = True                                                  
server_thread.start()                                                        
IP, PORT = server.socket.getsockname()                                       
PORT

**Comment by element-82** [comment]
dbb71afdcaa269a6588db509ebb47fab89c6739b fixes the issue
