### ISSUE TITLE
Device Manager does not accept command line arguments

### ISSUE THREAD

**Issue by EdMarks** [Wind-River/device-cloud-python#29]
All of the sample applications accept command line arguments; however, the device manager application does not.  It would be great if it did.

**Comment by jkeffer** [comment]
Without this fix, it is a poor user experience. 

The user needs to change the code to specify a configuration directory other than the current directory. On Linux, the user will probably want to use /etc/iot for the config directory and /usr/bin for the device manager executable. They should not need to change the code. They are now stuck maintaining the code to propagate their change.
