### ISSUE TITLE
Configuration entries for file upload are ignored

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#64]
The entries upload_remove_on_success and upload_additional_dirs in iot.cfg are not used for file upload. 

I specified upload_remove_on_success as true (the default) and files are not removed from the runtime/upload directory as expected.

I added a directory to upload_remove_on_success and the action returned Not Found. 

I don't see anything in the code that uses these entries.

**Comment by lcc755** [comment]
upload_additional_dirs has been removed. upload_remove_on_success doesn't have an issue anymore.
