### ISSUE TITLE
Device Manager: File download raises exception if the file already exists

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#66]
This might work differently on Windows and Linux.

I downloaded the same file to the same location. I expected it to either overwrite the existing file (previous behavior) or return an error to the cloud. Instead I get an exception on the device and timed out in the cloud. I'm not sure if the error is the device manager itself or if it is the underlying code and any application will see this if it uses the API.

Cloud output:

[
    "Timed Out"
]

Console output:
Oct 20 11:58:23 DEBUG: handler.py:965 - Received message on topic "notify/mailbox_activity"
{
  "sessionId": "59ea1494785a32576f4e3673",
  "thingKey": "a66a07d3-8755-4133-8f13-fe6c845d8dba-device_manager_py"
}
Oct 20 11:58:23 INFO: handler.py:611 - Recevied notification of mailbox activity
Oct 20 11:58:23 INFO: handler.py:1145 - MQTT queued 0005-1 - Mailbox Check
{
  "command": "mailbox.check",
  "params": {
    "autoComplete": false
  }
}
Oct 20 11:58:23 DEBUG: handler.py:978 - MQTT sent 0005
Oct 20 11:58:24 DEBUG: handler.py:965 - Received message on topic "reply/0005"
{
  "1": {
    "params": {
      "messages": [
        {
          "command": "method.exec",
          "expireTs": "2017-11-19T15:58:11.835Z",
          "expires": "2017-10-20T15:58:26.835Z",
          "from": "julia.keffer@windriver.com",
          "id": "59ea1d1374e936180b5faeb1",
          "params": {
            "method": "file_download",
            "params": {
              "file_name": "README.md",
              "file_path": "C:\\Users\\svc-iottest\\myreadme.txt",
              "use_global_store": false
            },
            "thingDefKey": "hdc_device_manager_def"
          },
          "thingKey": "a66a07d3-8755-4133-8f13-fe6c845d8dba-device_manager_py"
        }
      ]
    },
    "success": true
  }
}
Oct 20 11:58:24 INFO: handler.py:639 - Received success for 0005-1 - Mailbox Check
Oct 20 11:58:24 INFO: device_manager.py:225 - Downloading
Oct 20 11:58:24 INFO: handler.py:1005 - Request download of README.md
Oct 20 11:58:24 INFO: handler.py:1145 - MQTT queued 0006-1 - Download README.md
{
  "command": "file.get",
  "params": {
    "fileName": "README.md",
    "global": false,
    "thingKey": "a66a07d3-8755-4133-8f13-fe6c845d8dba-device_manager_py"
  }
}
Oct 20 11:58:24 DEBUG: handler.py:978 - MQTT sent 0006
Oct 20 11:58:24 DEBUG: handler.py:965 - Received message on topic "reply/0006"
{
  "1": {
    "params": {
      "crc32": 3582622335,
      "fileId": "59ea1d1374e936180b5faeb3",
      "fileSize": 777
    },
    "success": true
  }
}
Oct 20 11:58:24 INFO: handler.py:639 - Received success for 0006-1 - Download README.md
Oct 20 11:58:24 INFO: handler.py:470 - Downloading "README.md"
Oct 20 11:58:24 ERROR: handler.py:821 - Exception:
Traceback (most recent call last):
  File "C:\Users\svc-iottest\git\device-cloud-python\device_cloud\_core\handler.py", line 816, in handle_work_loop
    self.handle_file_download(work.data)
  File "C:\Users\svc-iottest\git\device-cloud-python\device_cloud\_core\handler.py", line 519, in handle_file_download
    os.rename(temp_path, download.file_path)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\svc-iottest\\4300182690.part' -> 'C:\\Users\\svc-iottest\\myreadme.txt'
Oct 20 11:58:39 INFO: handler.py:1145 - MQTT queued 0007-1 - Action Complete "file_download" result : 16(Timed Out) "Timed Out"
{
  "command": "mailbox.ack",
  "params": {
    "errorCode": 16,
    "errorMessage": "Timed Out",
    "id": "59ea1d1374e936180b5faeb1"
  }
}
Oct 20 11:58:39 DEBUG: handler.py:978 - MQTT sent 0007
Oct 20 11:58:39 DEBUG: handler.py:965 - Received message on topic "reply/0007"
{
  "1": {
    "success": true
  }
}
Oct 20 11:58:39 INFO: handler.py:639 - Received success for 0007-1 - Action Complete "file_download" result : 16(Timed Out) "Timed Out"

**Comment by element-82** [comment]
Windows is very fussy when handling files.   Is the file in use when you try to overwrite it?  We don't see this behaviour on mac on linux.

**Comment by jkeffer** [comment]
The file is not in use.
