### ISSUE TITLE
Remove certificate validation from config file examples and generate_config.py script

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#86]
Production environments should not run with certificate validation disabled. We can leave the options available in the code for our own use in a staging environment, but we should not show them in the example configuration files or prompt for them in the script that generates the configuration.

**Comment by element-82** [comment]
The config files for the demos have been removed.  They are not meant for public consumption.

**Comment by jkeffer** [comment]
The prompts are still there in the generate_config.py script.
