### ISSUE TITLE
Update admin-tools to add to support to thing defs for C sample applications

### ISSUE THREAD

**Issue by jkeffer** [Wind-River/device-cloud-python#94]
The sample C and Python applications have the same functionality but use different method names, attributes, properties, etc. 

Rather than changing the applications, it would be easiest to update the corresponding thing defs to cover both samples. For example, the simple telemetry app thing def include properties property-1, property-2 from the Python app and int8, int32, etc. from the C app. 

Also add a thing def for the C complete app.

**Comment by jkeffer** [comment]
Don't agree that this is an enhancement. Without at least one thing def that matches the C sample apps, they are useless.

**Comment by element-82** [comment]
This was fixed and the commit was added to device-cloud-lib.  Closing this issue.
