### ISSUE TITLE
iot-simple-location.py script will eventually publish invalid location coordinates

### ISSUE THREAD

**Issue by tonym-wrs** [Wind-River/device-cloud-python#96]
After connecting the iot-simple-location.py demo program to the cloud and toggling the location data on, valid location data is sent.  There is also a nice feature where the location data changes to simulate a device in motion.  After some time the calculation for lat and lon create values that are invalid.  This location data is published but we see error messages.  

Connect iot-simple-telemetry.py to cloud
Toggle Location On
--Let it run for a while (not sure how long it takes but probably a few hours)
Eventually it will calculate and publish bad location data.

Here is an example location:
Sep 26 07:01:32 INFO: iot-simple-location.py:137 - Publishing Location
Sep 26 07:01:33 INFO: handler.py:1079 - MQTT queued 11617-1 - Location Publish latitude: 109.6716030000005, longitude: -255.4287130000023, heading: 264.06984754831046, speed: 14.17
{
  "command": "location.publish",
  "params": {
    "heading": 264.06984754831046,
    "lat": 109.6716030000005,
    "lng": -255.4287130000023,
    "speed": 14.17,
    "thingKey": "c9f8b14d-08c7-431c-8c2f-7038dcb5e276-location_win_mfog_py36",
    "ts": "2017-09-26T14:01:32.948334Z"
  }
}
Sep 26 07:01:33 DEBUG: handler.py:911 - MQTT sent 11617
Sep 26 07:01:33 DEBUG: handler.py:898 - Received message on topic "reply/11617"
{
  "1": {
    "errorCodes": [
      -92605
    ],
    "errorMessages": [
      "Location is invalid."
    ],
    "success": false
  }
}
Sep 26 07:01:33 ERROR: handler.py:643 - Received failure for 11617-1 - Location Publish latitude: 109.6716030000005, longitude: -255.4287130000023, heading: 264.06984754831046, speed: 14.17
Sep 26 07:01:33 ERROR: handler.py:644 - .... {'success': False, 'errorMessages': ['Location is invalid.'], 'errorCodes': [-92605]}
Sep 26 07:01:37 INFO: iot-simple-location.py:137 - Publishing Location
Sep 26 07:01:37 INFO: handler.py:1079 - MQTT queued 11618-1 - Location Publish latitude: 109.6716030000005, longitude: -255.4487130000023, heading: 269.2998475483105, speed: 21.78
{
  "command": "location.publish",
  "params": {
    "heading": 269.2998475483105,
    "lat": 109.6716030000005,
    "lng": -255.4487130000023,
    "speed": 21.78,
    "thingKey": "c9f8b14d-08c7-431c-8c2f-7038dcb5e276-location_win_mfog_py36",
    "ts": "2017-09-26T14:01:37.001486Z"
  }
}
Sep 26 07:01:38 DEBUG: handler.py:911 - MQTT sent 11618
Sep 26 07:01:38 DEBUG: handler.py:898 - Received message on topic "reply/11618"
{
  "1": {
    "errorCodes": [
      -92605
    ],
    "errorMessages": [
      "Location is invalid."
    ],
    "success": false
  }
}

**Comment by lcc755** [comment]
I let it run for about 5 hours and never ran into this issue. Is there anything in particular you did?

**Comment by mafoglia** [comment]
Not that I recall.  Just kicked mine off and I'll check back in the am.
