### ISSUE TITLE
minor problems in share/admin_tools

### ISSUE THREAD

**Issue by tonym-wrs** [Wind-River/device-cloud-python#98]
Found a few subtle problems in share/admin_tools directory that should be fixed prior to initial release.  I've added git diff for each fix.

1.  share/admin_tools/README.md - The script in this directory does not ask the user for an ORG.  It will operate against the user's default org as specified in their profile.  I believe this information should be added to the README.md

2.  Telemetry spelled incorrectly in app_defs.  This can show up on IoT Portal so we should fix.

diff --git a/share/admin-tools/app_defs/demo_apps.cfg b/share/admin-tools/app_defs/demo_apps.cfg
index 14dd52f..09bbf48 100644
--- a/share/admin-tools/app_defs/demo_apps.cfg
+++ b/share/admin-tools/app_defs/demo_apps.cfg
@@ -14,7 +14,7 @@
         "license":""
     },
     {
-        "name":"hdc_simple_telmetry_app",
+        "name":"hdc_simple_telemetry_app",
         "desc":"hdc_simple_telemetry_app",
         "token":"",
         "autoRegThingDefId":"hdc_simple_telemetry_def",

3. File Upload->File Name on Cloud has incorrect type.

diff --git a/share/admin-tools/thing_defs/demo_defs.cfg b/share/admin-tools/thing_defs/demo_defs.cfg
index 6212f75..c7ee32d 100644
--- a/share/admin-tools/thing_defs/demo_defs.cfg
+++ b/share/admin-tools/thing_defs/demo_defs.cfg
@@ -88,7 +88,7 @@
                     "notificationVariables": {
                         "dest_name": {
                             "name": "File Name on Cloud (blank for same name)",
-                            "type": "bool",
+                            "type": "string",
                             "uiType": "text"
                         },
                         "file_name": {

4.  I believe the "auto:" elements should be removed from the hdc_device_manager_def thing definition.

diff --git a/share/admin-tools/thing_defs/hdc_device_manager_def.cfg b/share/admin-tools/thing_defs/hdc_device_manager_def.cfg
index 3c5dba6..29b39b5 100644
--- a/share/admin-tools/thing_defs/hdc_device_manager_def.cfg
+++ b/share/admin-tools/thing_defs/hdc_device_manager_def.cfg
@@ -6,20 +6,6 @@
         "version": 20,
         "autoDefProps": true,
         "autoDefAttrs": true,
-        "properties": {
-        "py_property_publish_int": {
-            "name": "auto:py_property_publish_int",
-            "calcAggregates": false
-        },
-        "test": {
-            "name": "auto:test",
-            "calcAggregates": false
-        },
-        "testing": {
-            "name": "auto:testing",
-            "calcAggregates": false
-        }
-        },
         "attributes": {
         "architecture": {
             "name": "System Architecture",
@@ -47,9 +33,6 @@
         "os_version": {
             "name": "Operating System Version",
             "default": "Unknown"
-        },
-        "platform": {
-            "name": "auto:platform"
         }
         },
         "alarms": {

**Comment by element-82** [comment]
Auto is fixed, but will add prompt for org and clean up the typos.
