### ISSUE TITLE
MAC address calculation in device_manager.py has bug - Windows

### ISSUE THREAD

**Issue by tonym-wrs** [Wind-River/device-cloud-python#99]
The following problem occurs when running hdc-python on Win7 box with Python 3.6. 

Running ipconfig /all on my Win7 box yields: 
Ethernet adapter Local Area Connection: 

   Connection-specific DNS Suffix . : corp.ad.wrs.com 
   Description . . . . . . . . . . . : Intel(R) 82567LM Gigabit Network Connecti 
on 
   Physical Address. . . . . . . . . : 00-21-70-BF-F8-11 
   DHCP Enabled. . . . . . . . . . . : Yes 
<snip> 

However, the IoT Portal shows: 
MAC Address 00:02:17:0B:FF:81 
in the 'Attributes' tab for my thing.

https://github.com/Wind-River/device-cloud-python/blob/5fe24b5c121f9f9ec695bfc965d59c50f089fa18/device_manager.py#L326

**Comment by mafoglia** [comment]
I see the following on Windows 10 Home:
Nov 19 11:00:15 INFO: handler.py:648 - Received success for 0001-7 - Attribute Publish mac_address : "C0:18:85:5F:C6:9D; 12:18:85:5F:C6:9D; 12:18:85:5F:C6:9D"
The first two MACs are wireless and not enabled.  The third MAC is incorrect; it should be my Ethernet interface which is active.
